name: Run Postman Tests

on:
  workflow_dispatch:
  push:

jobs:
  postman:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Inject Slack Webhook into Postman environment
        run: |
          jq --arg hook "$SLACK_WEBHOOK_URL" \
            '.values |= map(if .key=="SLACK_WEBHOOK_URL" then .value=$hook else . end)' \
            environment-template.json > environment.json

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run "postman/Sanity Test Production.postman_collection_1.json" \
            -e "environment.json" \
            -r cli,html \
            --reporter-html-export newman-report.html \
            --suppress-exit-code

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
