name: Run Postman Tests

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "30 3 * * *"   # 9:00 AM IST
    - cron: "30 11 * * *"  # 5:00 PM IST
    - cron: "30 15 * * *"  # 9:00 PM IST

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node and Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Debug Slack Secret
        run: |
          if [ -z "${SLACK_WEBHOOK_URL}" ]; then
            echo "❌ SLACK_WEBHOOK_URL is EMPTY"
          else
            echo "✔ SLACK_WEBHOOK_URL loaded: ${SLACK_WEBHOOK_URL:0:20}..."
          fi
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Run Postman Tests
        run: |
          newman run "postman/Sanity Test Production.postman_collection_1.json" \
            --env-var SLACK_WEBHOOK_URL="${SLACK_WEBHOOK_URL}" \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman-report.html \
            --suppress-exit-code
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
