name: Run Postman Tests

on:
  workflow_dispatch:
  push:

jobs:
  postman:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js & Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Debug Slack URL
        run: |
          echo "Slack Secret (first 20 chars): ${SLACK_WEBHOOK_URL:0:20}"

      - name: Debug Postman Collection for Slack variable
        run: |
          echo "Checking if SLACK_WEBHOOK_URL exists in collection..."
          grep -R "SLACK_WEBHOOK_URL" -n "postman/Sanity Test Production.postman_collection_1.json"

      - name: Run Postman Tests
        run: |
          newman run "postman/Sanity Test Production.postman_collection_1.json" \
            --global-var "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}" \
            -r cli,html \
            --reporter-html-export newman-report.html \
            --suppress-exit-code
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
